<?php
return array(
    'goodscategory'=>array(
        'title'=>'产品分类',
        'items'=>array(
            'index'=>'内容分类查看',
            'add'=>'内容分类添加',
            'edit'=>'内容分类修改',
            'delete'=>'内容分类删除'
        )
    ),
    'goods'=>array(
        'title'=>'商品管理',
        'items'=>array(
            'index'=>'商品查看',
            'add'=>'商品添加',
            'edit'=>'商品修改',
            'delete'=>'商品删除'
        )
    ),
    'storage'=>array(
        'title'=>'仓库管理',
        'items'=>array(
            'index'=>'仓库查看',
            'add'=>'仓库添加',
            'edit'=>'仓库修改',
            'delete'=>'仓库删除'
        )
    ),
    'transorder'=>array(
        'title'=>'转库管理',
        'items'=>array(
            'index'=>'订单查看',
            'create'=>'转库下单',
            'delete'=>'订单删除',
            'status'=>'订单状态',
        )
    ),
    'supplier'=>array(
        'title'=>'供应商管理',
        'items'=>array(
            'index'=>'供应商查看',
            'add'=>'供应商添加',
            'edit'=>'供应商修改',
            'delete'=>'供应商删除'
        )
    ),
    'purchaseorder'=>array(
        'title'=>'采购管理',
        'items'=>array(
            'index'=>'订单查看',
            'create'=>'采购下单',
            'delete'=>'订单删除',
            'status'=>'订单状态',
        )
    ),
    'customer'=>array(
        'title'=>'客户管理',
        'items'=>array(
            'index'=>'客户查看',
            'add'=>'客户添加',
            'edit'=>'客户修改',
            'delete'=>'客户删除'
        )
    ),
    'saleorder'=>array(
        'title'=>'销售管理',
        'items'=>array(
            'index'=>'订单查看',
            'create'=>'销售下单',
            'delete'=>'订单删除',
            'status'=>'订单状态',
        )
    ),
    'finance'=>array(
        'title'=>'财务管理',
        'items'=>array(
            'index'=>'财务总览',
            'receive'=>'收款管理',
            'receivelog'=>'收款录入',
            'receivedetail'=>'收款详情',
            'payable'=>'付款管理',
            'payablelog'=>'付款录入',
            'payabledetail'=>'付款详情',
            'logs'=>'财务明细',
        )
    ),
    'data'=>array(
        'title'=>'基础数据',
        'items'=>array(
            'index'=>'基础数据管理',
        )
    ),
    'setting'=>array(
        'title'=>'系统配置',
        'items'=>array(
            'index'=>'系统配置',
            'import'=>'配置导入',
            'export'=>'配置导出',
            'advance'=>'配置管理',
            'add'=>'配置添加',
            'edit'=>'配置修改',
            'delete'=>'配置删除'
        )
    ),
    'manager'=>array(
        'title'=>'管理员',
        'items'=>array(
            'index'=>'管理员查看',
            'add'=>'管理员添加',
            'edit'=>'管理员修改',
            'log'=>'操作日志',
            'delete'=>'管理员删除'
        )
    ),
);
//end